name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Streamlit App
        run: streamlit run main.py
        
      - name: Debug print env variable
        run: echo "OMDB_API_KEY is $OMDB_API_KEY"
