name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # ganti ke 3.10 agar aman

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug check API Key
        run: echo "KEY: $OMDB_API_KEY"  # opsional, bisa dihapus nanti

      - name: Run Streamlit App
        run: streamlit run main.py
